### ISSUE TITLE
Error: Cannot find native module 'ExpoAlarm'

### ISSUE THREAD

**Issue by lennertderyck** [alperengozum/expo-alarm#2]
After installing the package I get the following error in the terminal:

```bash
ERROR  Error: Cannot find native module 'ExpoAlarm', js engine: hermes
ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```
Is there additional setup required to get it working?

**Comment by alperengozum** [comment]
Hi @lennertderyck,
I investigated the issue but couldn't find the reason. I tried to use New [Expo's new Creating a Native Module Tutorial,](https://docs.expo.dev/modules/native-module-tutorial/) but unfortunately it gives the same error just after creating a new module.

**Comment by znadir** [comment]
You are getting this error because you can't run native code on Expo Go but only Expo SDK. You will need to use development build

https://docs.expo.dev/workflow/customizing/

**Comment by alperengozum** [comment]
I fixed a related issue with merging codes to the new native module structure: https://github.com/Alperengozum/expo-alarm/pull/3.
Please use version 0.2.0 and give some comments if this issue is fixed or continuing. 
I wish you healthy days! 🪄
