### ISSUE TITLE
 ERROR  Error: Cannot find native module 'ExpoAlarm', js engine: hermes 

### ISSUE THREAD

**Issue by biplabroy-1** [alperengozum/expo-alarm#5]
Hello Alperengozum,

i used your expo-alarm app example by git clone

and i also used in a expo blank project
and 2 cases i am getting the same error

 ERROR  Error: Cannot find native module 'ExpoAlarm', js engine: hermes
 
my code look like this 

// App.js

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, Button } from 'react-native';
import { setAlarm } from 'expo-alarm';

export default function App() {
  const setAlarmParams = {
    hour: 8,
    minutes: 30,
    days: [1, 2, 3],
    message: 'Wake up!',
    //ringtoneUri: 'exampleRingtoneUri',
    vibrate: true,
    skipUi: false,
    //extra: { customData: 'exampleData' },
  };
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Button
        title="Set alarm"
        onPress={async () => {
          try {
            await setAlarm(setAlarmParams);
            console.log('Alarm set successfully');
          } catch (e) {
            console.error('Failed to set alarm', e);
          }
        }}></Button>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

please help me to fix the issue

**Comment by alperengozum** [comment]
Hi @biplabroy-1,

I fixed this issue in **v0.2.0**. Please be sure to use version **0.2.0**.

I followed these steps, and it works perfectly:

```bash
git clone https://github.com/Alperengozum/expo-alarm
cd expo-alarm/example
npm i  # or yarn install
npm run android
```

Feel free to reach out if you have any questions!

**Comment by biplabroy-1** [comment]
wow idk how it work now but i do the same thing like one hour ago 

but anyways thank you ;)
can we see and dismiss all alarms without open the native clock app??

also you can add feture to add more alarm and dismiss it by id and show all without open the app

@Alperengozum

**Comment by biplabroy-1** [comment]
hello @Alperengozum 

i am getting this error while i use days 

<Button
        title="Set Alarm"
        onPress={async () => {
          const res = await ExpoAlarm.setAlarm({
            hour: 19,
            minutes: 46,
            days: [1, 2, 3],
            message: "Alarm",
            vibrate: true,
            skipUi: false,
          });
          console.log(res);
        }}
      />
      
      
![Screenshot_1730558496](https://github.com/user-attachments/assets/a963e4ab-d2f7-46d8-afaf-f3d10613a685)

**Comment by alperengozum** [comment]
Hi @biplabroy-1,
I'm closing this issue now.
If you have any other issues, please feel free to create a new one. Thanks for your understanding! 🙏🏻
