### ISSUE TITLE
installed via npm is not working

### ISSUE THREAD

**Issue by biplabroy-1** [alperengozum/expo-alarm#7]
Hi @Alperengozum 

i used your packege and i found if you download the 0.2.1
then it show the Error: Cannot find native module 'ExpoAlarm' 

you need to download the 0.2.0 version for perfect use

can you add .showAlarms();
return a array of all alarms.

**Comment by alperengozum** [comment]
Hi @biplabroy-1,

I just tested 0.2.1 with my open source project, and it works fine. [Sleepwell Github URL](https://github.com/Alperengozum/Sleepwell)
Also, there is no difference between 0.2.0 and 0.2.1; it was just a fix for the README.md issue for the [NPM package](https://www.npmjs.com/package/expo-alarm). 

Could you test with remove node_modules, remove existing app on emulator, and fresh install it?

**Comment by alperengozum** [comment]
> can you add .showAlarms();
return a array of all alarms.

Unfortunately, Android AlarmClock does not provide us with a list of all alarms. 
It only shows alarms and the reason that I implemented it like that.
 [Android AlarmClock Reference](https://developer.android.com/reference/android/provider/AlarmClock.html)
